apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
  namespace: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: 305018987435.dkr.ecr.eu-north-1.amazonaws.com/backend:8a35e9c01d3503b81adec25fb7d6245333b645bd
        name: backend
        ports:
        - containerPort: 8000
        resources: 
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 128Mi
        envFrom:
        - configMapRef:
            name: backend-config
        env:
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD

